[envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]

[envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report --show-missing",
]
cov = [
  "test-cov",
  "cov-report",
]

[envs.all]
type = "container"

[[envs.all.matrix]]
python = ["3.7", "3.8", "3.9", "3.10", "3.11"]

[envs.lint]
detached = true
dependencies = [
  "black==24.3.0",
  "isort==5.13.2"
]

[envs.lint.scripts]
style = [
  "black --check --diff {args:.}",
  "isort --check --diff --profile=black {args:.}"
]
fmt = [
  "black {args:.}",
  "isort --profile=black {args:.}",
  "style"
]
all = [
  "style",
]